### PR TITLE
Added for root async module register

### LINKED ISSUE #7: Register using forRootAsync
I need to be able to inject the prisma service.

https://www.npmjs.com/package/nestjs-prisma-module
https://www.npmjs.com/package/nestjs-prisma

However I cannot do that unless I can register this module asynchronously. A `forRootAsync` method needs added.

### PR DESCRIPTION
**Pull request by codejamninja**
Closes #7

### CODE REVIEW

**Review by MichalLytek — CHANGES_REQUESTED** [review]
I'm not sure which issue you're resolving 😕 

In #7 you're referring to use dynamic module to inject the PrismaModule.
However, `TypeGraphQLModule.forRoot` method already returns `DynamicModule`.

Could you enhance your PR by adding example 4. which leverage the dynamic module and your `forRootAsync` to show me and other users how to use it and when (in which context)?
Also, could you add info in Readme about the `forRootAsync` method and in which cases you may need this?

Thanks for your contribution! ❤️

**Comment by codejamninja** [comment]
Here is an example. You can see I need to inject the PrismaService into the GraphQL configuration.

https://github.com/codejamninja/nestjs-keycloak/blob/master/example/src/app.module.ts#L68

**Comment by nino-vrijman** [comment]
@codejamninja example is exactly how I would want to use the `forRootAsync` function to register the TypeGraphQL-Nest module too!

**Comment by codejamninja** [comment]
@nino-vrijman you can use `@codejamninja/typegraphql-nestjs` temporarily until there an official solution.

**Review by MichalLytek — APPROVED** [review]

**Comment by MichalLytek** [comment]
@codejamninja Thanks for your contribution! ❤️ 
I personally don't use Nest too much so if you have any other suggestions about the integration, feel free to open another issue 😉 

I've cleaned up the codebase a bit and added readme entry about the new `forRootAsync` feature, so now I'm merging it 🚀

**Pull request merged**
